version: '2'

services:
  rq_dashboard:
    container_name: rq_dashboard
    hostname: rq_dashboard
    build:
      context: ../services/rq_dashboard
    image: rq_dashboard
    ports:
      - "4444:4444"
  redis:
    container_name: redis
    image: redis
    restart: always

  population_analyzer:
    container_name: population_analyzer
    hostname: population_analyzer
    image: population_analyzer
    build:
      context: ../services/population_analyzer
      args:
        PYPI_SERVER_SCHEME:
        PYPI_SERVER_HOST:
        PYPI_SERVER_PORT:

  private_github_crawler:
    container_name: private_github_crawler
    hostname: private_github_crawler
    image: private_github_crawler
    build:
      context: ../services/private_github_crawler
      args:
        PYPI_SERVER_SCHEME:
        PYPI_SERVER_HOST:
        PYPI_SERVER_PORT:
    environment:
      CRAWLER_USERNAME:
      CRAWLER_PASSWORD:

  public_github_crawler:
    container_name: public_github_crawler
    hostname: public_github_crawler
    image: public_github_crawler
    build:
      context: ../services/public_github_crawler
      args:
        PYPI_SERVER_SCHEME:
        PYPI_SERVER_HOST:
        PYPI_SERVER_PORT:
    environment:
      CRAWLER_USERNAME:
      CRAWLER_PASSWORD:

  default_queue:
    container_name: default_queue
    hostname: default_queue
    image: default_queue
    build:
      context: ../services/default_queue
      args:
        PYPI_SERVER_SCHEME:
        PYPI_SERVER_HOST:
        PYPI_SERVER_PORT:
    environment:
      CRAWLER_USERNAME:
      CRAWLER_PASSWORD:
      # SETTINGS: ".rq_default.config"
      # make sure the following number matches the tmpfs size
      REPOS_VOLUME_SIZE_IN_MB: 500

      # Should be roughly 20 * (REPOS_VOLUME_SIZE_IN_MB ^ (-1/3))
      CLONE_SIZE_SAFETY_FACTOR: 2
    tmpfs:
     - /repos:rw,noexec,size=500m
