version: '2'

services:
  rq_dashboard:
    extends:
      file: common.yml
      service: rq_dashboard
  redis:
    extends:
      file: common.yml
      service: redis
  default_queue:
    extends:
      file: common.yml
      service: default_queue
    environment:
      LOG_LEVEL: "DEBUG"
  private_github_crawler:
    extends:
      file: common.yml
      service: private_github_crawler
    environment:
      LOG_LEVEL: "DEBUG"
  public_github_crawler:
    extends:
      file: common.yml
      service: public_github_crawler
    environment:
      LOG_LEVEL: "DEBUG"
  population_analyzer:
    extends:
      file: common.yml
      service: population_analyzer
    environment:
      LOG_LEVEL: "DEBUG"
